name: publish

on:
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: "3.13"
      - run: python -m pip install build twine
      - run: python -m build
      - run: python -m twine check dist/*
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/adaptkit
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@v1.14.2
